version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-api-demo
    container_name: github-api-demo
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    networks:
      - backend
    depends_on: 
      - redis
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend


networks:
  backend: